### ISSUE TITLE
Github Releases in CI Promote

### ISSUE THREAD

**Issue by Everlag** [cloudfoundry/bosh-gcscli#14]
Currently, the concourse pipeline's `promote` job tags a specific commit. In the future, it'd be preferable to have full github releases which would include the binary.

One potential option is to use concourse's [github-release-resource](https://github.com/concourse/github-release-resource).

**Comment by cppforlife** [comment]
not planning to add github releases for now, as ci produced binaries are referenced directly by the upstream repos (like stemcell builder).
