### ISSUE TITLE
Update golang version in pipeline for building the bosh-gcscli

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry/bosh-gcscli#25]
It appears that we are still using [golang 1.8.3](https://github.com/cloudfoundry/bosh-gcscli/blob/master/ci/docker-image/Dockerfile#L16) in CI for building/publishing the bosh-gcscli artifact. We should update this to a more recent version of Golang.

**Comment by cjnosal** [comment]
master has 1.12.9 now
